
   Name           Domain             Range
   ----------------------------------------
   D 0            .1                 .2
   ----------------------------------------
   add            <.3,.4>            .1
   ----------------------------------------

 Directions -  <in,in> ~ <out>

 Wiring -  <.3,.4> ~ <.2>

 Inputs -  .3 .4
