
   Name           Domain             Range
   ----------------------------------------
   D 0            .1                 .2
   ----------------------------------------
   add            <.3,.2>            .1
   ----------------------------------------

 Directions -  <in> ~ <out>

 Wiring -  <.3> ~ <.2>

 Inputs -  .3
