
   Name           Domain             Range
   ----------------------------------------
   D 0            .1                 .2
   D 0            .3                 .4
   D 0            .5                 .6
   D 0            .2                 .7
   D 0            .8                 .9
   D 0            .10                .11
   D 0            .12                .13
   D 0            .14                .15
   D 0            .16                .17
   D 0            .13                .18
   D 0            .19                .20
   D 0            .21                .22
   D 0            .23                .24
   D 0            .25                .26
   D 0            .27                .28
   D 0            .24                .29
   D 0            .30                .31
   D 0            .32                .33
   D 0            .34                .35
   D 0            .36                .37
   D 0            .38                .39
   D 0            .35                .40
   D 0            .41                .42
   D 0            .43                .44
   ----------------------------------------
   mult           <.45,.46>          .1
   mult           <.47,.48>          .3
   mult           <.49,.50>          .5
   add            <.4,.6>            .8
   add            <.7,.9>            .10
   mult           <.51,.46>          .12
   mult           <.52,.48>          .14
   mult           <.53,.50>          .16
   add            <.15,.17>          .19
   add            <.18,.20>          .21
   mult           <.54,.46>          .23
   mult           <.55,.48>          .25
   mult           <.56,.50>          .27
   add            <.26,.28>          .30
   add            <.29,.31>          .32
   mult           <.57,.46>          .34
   mult           <.58,.48>          .36
   mult           <.59,.50>          .38
   add            <.37,.39>          .41
   add            <.40,.42>          .43
   AD             .11                .60
   AD             .22                .61
   AD             .33                .62
   AD             .44                .63
   ----------------------------------------
   AD             .60                .64
   AD             .61                .65
   AD             .62                .66
   AD             .63                .67
   ----------------------------------------
   AD             .64                .68
   AD             .65                .69
   AD             .66                .70
   AD             .67                .71
   ----------------------------------------

 Directions -  <<<in,in,in>,<in,in,in>,<in,in,in>,<in,in,in>>,<in,in,in>> ~ <out,out,out,out>

 Wiring -  <<<.45,.47,.49>,<.51,.52,.53>,<.54,.55,.56>,<.57,.58,.59>>,<.46,.48,.50>> ~ <.68,.69,.70,.71>

 Inputs -  .45 .47 .49 .51 .52 .53 .54 .55 .56 .57 .58 .59 .46 .48 .50
