
   Name           Domain             Range
   ----------------------------------------
   D 0            .1                 .2
   D 0            .3                 .4
   D 0            .5                 .6
   D 0            .2                 .7
   D 0            .8                 .9
   D 0            .10                .11
   D 0            .12                .13
   D 0            .14                .15
   D 0            .16                .17
   D 0            .13                .18
   D 0            .19                .20
   D 0            .21                .22
   D 0            .23                .24
   D 0            .25                .26
   D 0            .27                .28
   D 0            .24                .29
   D 0            .30                .31
   D 0            .32                .33
   ----------------------------------------
   mult           <.34,.35>          .1
   mult           <.36,.37>          .3
   mult           <.38,.39>          .5
   add            <.4,.6>            .8
   add            <.7,.9>            .10
   mult           <.36,.35>          .12
   mult           <.38,.37>          .14
   mult           <.40,.39>          .16
   add            <.15,.17>          .19
   add            <.18,.20>          .21
   mult           <.38,.35>          .23
   mult           <.40,.37>          .25
   mult           <.41,.39>          .27
   add            <.26,.28>          .30
   add            <.29,.31>          .32
   ----------------------------------------

 Directions -  <<in,in,in,in,in>,<in,in,in>> ~ <out,out,out>

 Wiring -  <<.34,.36,.38,.40,.41>,<.35,.37,.39>> ~ <.11,.22,.33>

 Inputs -  .34 .36 .38 .40 .41 .35 .37 .39
