
   Name           Domain             Range
   ----------------------------------------
   D 0            .1                 .2
   D 0            .3                 .4
   D 0            .5                 .6
   D 0            .7                 .8
   D 0            .9                 .10
   D 0            .11                .12
   D 0            .13                .14
   D 0            .15                .16
   D 0            .17                .18
   D 0            .2                 .19
   D 0            .20                .21
   D 0            .22                .23
   D 0            .24                .25
   D 0            .26                .27
   D 0            .19                .28
   D 0            .29                .30
   D 0            .31                .32
   D 0            .28                .33
   D 0            .34                .35
   D 0            .36                .37
   D 0            .38                .39
   D 0            .40                .41
   D 0            .42                .43
   D 0            .44                .45
   D 0            .46                .47
   D 0            .48                .49
   D 0            .50                .51
   D 0            .52                .53
   D 0            .54                .55
   D 0            .39                .56
   D 0            .57                .58
   D 0            .59                .60
   D 0            .61                .62
   D 0            .63                .64
   D 0            .56                .65
   D 0            .66                .67
   D 0            .68                .69
   D 0            .65                .70
   D 0            .71                .72
   D 0            .73                .74
   D 0            .75                .76
   D 0            .77                .78
   D 0            .79                .80
   D 0            .81                .82
   D 0            .83                .84
   D 0            .85                .86
   D 0            .87                .88
   D 0            .89                .90
   D 0            .91                .92
   D 0            .76                .93
   D 0            .94                .95
   D 0            .96                .97
   D 0            .98                .99
   D 0            .100               .101
   D 0            .93                .102
   D 0            .103               .104
   D 0            .105               .106
   D 0            .102               .107
   D 0            .108               .109
   D 0            .110               .111
   D 0            .112               .113
   D 0            .114               .115
   D 0            .116               .117
   D 0            .118               .119
   D 0            .120               .121
   D 0            .122               .123
   D 0            .124               .125
   D 0            .126               .127
   D 0            .128               .129
   D 0            .113               .130
   D 0            .131               .132
   D 0            .133               .134
   D 0            .135               .136
   D 0            .137               .138
   D 0            .130               .139
   D 0            .140               .141
   D 0            .142               .143
   D 0            .139               .144
   D 0            .145               .146
   D 0            .147               .148
   D 0            .149               .150
   D 0            .151               .152
   D 0            .153               .154
   D 0            .155               .156
   D 0            .157               .158
   D 0            .159               .160
   D 0            .161               .162
   D 0            .163               .164
   D 0            .165               .166
   D 0            .150               .167
   D 0            .168               .169
   D 0            .170               .171
   D 0            .172               .173
   D 0            .174               .175
   D 0            .167               .176
   D 0            .177               .178
   D 0            .179               .180
   D 0            .176               .181
   D 0            .182               .183
   D 0            .184               .185
   D 0            .186               .187
   D 0            .188               .189
   D 0            .190               .191
   D 0            .192               .193
   D 0            .194               .195
   D 0            .196               .197
   D 0            .198               .199
   D 0            .200               .201
   D 0            .202               .203
   D 0            .187               .204
   D 0            .205               .206
   D 0            .207               .208
   D 0            .209               .210
   D 0            .211               .212
   D 0            .204               .213
   D 0            .214               .215
   D 0            .216               .217
   D 0            .213               .218
   D 0            .219               .220
   D 0            .221               .222
   D 0            .223               .224
   D 0            .225               .226
   D 0            .227               .228
   D 0            .229               .230
   D 0            .231               .232
   D 0            .233               .234
   D 0            .235               .236
   D 0            .237               .238
   D 0            .239               .240
   D 0            .224               .241
   D 0            .242               .243
   D 0            .244               .245
   D 0            .246               .247
   D 0            .248               .249
   D 0            .241               .250
   D 0            .251               .252
   D 0            .253               .254
   D 0            .250               .255
   D 0            .256               .257
   D 0            .258               .259
   D 0            .260               .261
   D 0            .262               .263
   D 0            .264               .265
   D 0            .266               .267
   D 0            .268               .269
   D 0            .270               .271
   D 0            .272               .273
   D 0            .274               .275
   D 0            .276               .277
   D 0            .261               .278
   D 0            .279               .280
   D 0            .281               .282
   D 0            .283               .284
   D 0            .285               .286
   D 0            .278               .287
   D 0            .288               .289
   D 0            .290               .291
   D 0            .287               .292
   D 0            .293               .294
   D 0            .295               .296
   D 0            .297               .298
   D 0            .299               .300
   D 0            .301               .302
   D 0            .303               .304
   D 0            .305               .306
   D 0            .307               .308
   D 0            .309               .310
   D 0            .311               .312
   D 0            .313               .314
   D 0            .298               .315
   D 0            .316               .317
   D 0            .318               .319
   D 0            .320               .321
   D 0            .322               .323
   D 0            .315               .324
   D 0            .325               .326
   D 0            .327               .328
   D 0            .324               .329
   D 0            .330               .331
   D 0            .332               .333
   ----------------------------------------
   mult           <.334,.335>        .1
   mult           <.336,.337>        .3
   mult           <.338,.339>        .5
   mult           <.340,.341>        .7
   mult           <.342,.343>        .9
   mult           <.344,.345>        .11
   mult           <.346,.347>        .13
   mult           <.348,.349>        .15
   mult           <.350,.351>        .17
   add            <.4,.6>            .20
   add            <.8,.10>           .22
   add            <.12,.14>          .24
   add            <.16,.18>          .26
   add            <.21,.23>          .29
   add            <.25,.27>          .31
   add            <.30,.32>          .34
   add            <.33,.35>          .36
   mult           <.336,.335>        .38
   mult           <.338,.337>        .40
   mult           <.352,.339>        .42
   mult           <.342,.341>        .44
   mult           <.344,.343>        .46
   mult           <.353,.345>        .48
   mult           <.348,.347>        .50
   mult           <.350,.349>        .52
   mult           <.354,.351>        .54
   add            <.41,.43>          .57
   add            <.45,.47>          .59
   add            <.49,.51>          .61
   add            <.53,.55>          .63
   add            <.58,.60>          .66
   add            <.62,.64>          .68
   add            <.67,.69>          .71
   add            <.70,.72>          .73
   mult           <.338,.335>        .75
   mult           <.352,.337>        .77
   mult           <.355,.339>        .79
   mult           <.344,.341>        .81
   mult           <.353,.343>        .83
   mult           <.356,.345>        .85
   mult           <.350,.347>        .87
   mult           <.354,.349>        .89
   mult           <.357,.351>        .91
   add            <.78,.80>          .94
   add            <.82,.84>          .96
   add            <.86,.88>          .98
   add            <.90,.92>          .100
   add            <.95,.97>          .103
   add            <.99,.101>         .105
   add            <.104,.106>        .108
   add            <.107,.109>        .110
   mult           <.340,.335>        .112
   mult           <.342,.337>        .114
   mult           <.344,.339>        .116
   mult           <.346,.341>        .118
   mult           <.348,.343>        .120
   mult           <.350,.345>        .122
   mult           <.358,.347>        .124
   mult           <.359,.349>        .126
   mult           <.360,.351>        .128
   add            <.115,.117>        .131
   add            <.119,.121>        .133
   add            <.123,.125>        .135
   add            <.127,.129>        .137
   add            <.132,.134>        .140
   add            <.136,.138>        .142
   add            <.141,.143>        .145
   add            <.144,.146>        .147
   mult           <.342,.335>        .149
   mult           <.344,.337>        .151
   mult           <.353,.339>        .153
   mult           <.348,.341>        .155
   mult           <.350,.343>        .157
   mult           <.354,.345>        .159
   mult           <.359,.347>        .161
   mult           <.360,.349>        .163
   mult           <.361,.351>        .165
   add            <.152,.154>        .168
   add            <.156,.158>        .170
   add            <.160,.162>        .172
   add            <.164,.166>        .174
   add            <.169,.171>        .177
   add            <.173,.175>        .179
   add            <.178,.180>        .182
   add            <.181,.183>        .184
   mult           <.344,.335>        .186
   mult           <.353,.337>        .188
   mult           <.356,.339>        .190
   mult           <.350,.341>        .192
   mult           <.354,.343>        .194
   mult           <.357,.345>        .196
   mult           <.360,.347>        .198
   mult           <.361,.349>        .200
   mult           <.362,.351>        .202
   add            <.189,.191>        .205
   add            <.193,.195>        .207
   add            <.197,.199>        .209
   add            <.201,.203>        .211
   add            <.206,.208>        .214
   add            <.210,.212>        .216
   add            <.215,.217>        .219
   add            <.218,.220>        .221
   mult           <.346,.335>        .223
   mult           <.348,.337>        .225
   mult           <.350,.339>        .227
   mult           <.358,.341>        .229
   mult           <.359,.343>        .231
   mult           <.360,.345>        .233
   mult           <.363,.347>        .235
   mult           <.364,.349>        .237
   mult           <.365,.351>        .239
   add            <.226,.228>        .242
   add            <.230,.232>        .244
   add            <.234,.236>        .246
   add            <.238,.240>        .248
   add            <.243,.245>        .251
   add            <.247,.249>        .253
   add            <.252,.254>        .256
   add            <.255,.257>        .258
   mult           <.348,.335>        .260
   mult           <.350,.337>        .262
   mult           <.354,.339>        .264
   mult           <.359,.341>        .266
   mult           <.360,.343>        .268
   mult           <.361,.345>        .270
   mult           <.364,.347>        .272
   mult           <.365,.349>        .274
   mult           <.366,.351>        .276
   add            <.263,.265>        .279
   add            <.267,.269>        .281
   add            <.271,.273>        .283
   add            <.275,.277>        .285
   add            <.280,.282>        .288
   add            <.284,.286>        .290
   add            <.289,.291>        .293
   add            <.292,.294>        .295
   mult           <.350,.335>        .297
   mult           <.354,.337>        .299
   mult           <.357,.339>        .301
   mult           <.360,.341>        .303
   mult           <.361,.343>        .305
   mult           <.362,.345>        .307
   mult           <.365,.347>        .309
   mult           <.366,.349>        .311
   mult           <.367,.351>        .313
   add            <.300,.302>        .316
   add            <.304,.306>        .318
   add            <.308,.310>        .320
   add            <.312,.314>        .322
   add            <.317,.319>        .325
   add            <.321,.323>        .327
   add            <.326,.328>        .330
   add            <.329,.331>        .332
   ----------------------------------------

 Directions -  <<<in,in,in,in,in>,<in,in,in,in,in>,<in,in,in,in,in>,<in,in,in,in,in>,<in,in,in,in,in>>,<<in,in,in>,<in,in,in>,<in,in,in>>> ~ <<out,out,out>,<out,out,out>,<out,out,out>>

 Wiring -  <<<.334,.336,.338,.352,.355>,<.340,.342,.344,.353,.356>,<.346,.348,.350,.354,.357>,<.358,.359,.360,.361,.362>,<.363,.364,.365,.366,.367>>,<<.335,.337,.339>,<.341,.343,.345>,<.347,.349,.351>>> ~ <<.37,.74,.111>,<.148,.185,.222>,<.259,.296,.333>>

 Inputs -  .334 .336 .338 .352 .355 .340 .342 .344 .353 .356 .346 .348 .350 .354 .357 .358 .359 .360 .361 .362 .363 .364 .365 .366 .367 .335 .337 .339 .341 .343 .345 .347 .349 .351
