
   Name           Domain             Range
   ----------------------------------------
   D 0            .1                 .2
   D 0            .3                 .4
   D 0            .5                 .6
   D 0            .7                 .8
   D 0            .9                 .10
   D 0            .2                 .11
   D 0            .12                .13
   D 0            .14                .15
   D 0            .11                .16
   D 0            .17                .18
   D 0            .19                .20
   D 0            .21                .22
   D 0            .23                .24
   D 0            .25                .26
   D 0            .27                .28
   D 0            .29                .30
   D 0            .22                .31
   D 0            .32                .33
   D 0            .34                .35
   D 0            .31                .36
   D 0            .37                .38
   D 0            .39                .40
   D 0            .41                .42
   D 0            .43                .44
   D 0            .45                .46
   D 0            .47                .48
   D 0            .49                .50
   D 0            .42                .51
   D 0            .52                .53
   D 0            .54                .55
   D 0            .51                .56
   D 0            .57                .58
   D 0            .59                .60
   D 0            .61                .62
   D 0            .63                .64
   D 0            .65                .66
   D 0            .67                .68
   D 0            .69                .70
   D 0            .62                .71
   D 0            .72                .73
   D 0            .74                .75
   D 0            .71                .76
   D 0            .77                .78
   D 0            .79                .80
   D 0            .81                .82
   D 0            .83                .84
   D 0            .85                .86
   D 0            .87                .88
   D 0            .89                .90
   D 0            .82                .91
   D 0            .92                .93
   D 0            .94                .95
   D 0            .91                .96
   D 0            .97                .98
   D 0            .99                .100
   D 0            .101               .102
   D 0            .103               .104
   D 0            .105               .106
   D 0            .107               .108
   D 0            .109               .110
   D 0            .102               .111
   D 0            .112               .113
   D 0            .114               .115
   D 0            .111               .116
   D 0            .117               .118
   D 0            .119               .120
   D 0            .121               .122
   D 0            .123               .124
   D 0            .125               .126
   D 0            .127               .128
   D 0            .129               .130
   D 0            .122               .131
   D 0            .132               .133
   D 0            .134               .135
   D 0            .131               .136
   D 0            .137               .138
   D 0            .139               .140
   D 0            .141               .142
   D 0            .143               .144
   D 0            .145               .146
   D 0            .147               .148
   D 0            .149               .150
   D 0            .142               .151
   D 0            .152               .153
   D 0            .154               .155
   D 0            .151               .156
   D 0            .157               .158
   D 0            .159               .160
   D 0            .161               .162
   D 0            .163               .164
   D 0            .165               .166
   D 0            .167               .168
   D 0            .169               .170
   D 0            .162               .171
   D 0            .172               .173
   D 0            .174               .175
   D 0            .171               .176
   D 0            .177               .178
   D 0            .179               .180
   ----------------------------------------
   max            <.181,.21>         .3
   max            <.182,.183>        .5
   max            <.184,.61>         .7
   max            <.185,.81>         .9
   max            <.4,.6>            .12
   max            <.8,.10>           .14
   max            <.13,.15>          .17
   max            <.16,.18>          .19
   max            <.186,.41>         .23
   max            <.184,.187>        .25
   max            <.188,.81>         .27
   max            <.189,.101>        .29
   max            <.24,.26>          .32
   max            <.28,.30>          .34
   max            <.33,.35>          .37
   max            <.36,.38>          .39
   max            <.190,.191>        .43
   max            <.188,.192>        .45
   max            <.193,.101>        .47
   max            <.194,.195>        .49
   max            <.44,.46>          .52
   max            <.48,.50>          .54
   max            <.53,.55>          .57
   max            <.56,.58>          .59
   max            <.185,.81>         .63
   max            <.196,.197>        .65
   max            <.198,.121>        .67
   max            <.199,.141>        .69
   max            <.64,.66>          .72
   max            <.68,.70>          .74
   max            <.73,.75>          .77
   max            <.76,.78>          .79
   max            <.189,.101>        .83
   max            <.198,.200>        .85
   max            <.201,.141>        .87
   max            <.202,.161>        .89
   max            <.84,.86>          .92
   max            <.88,.90>          .94
   max            <.93,.95>          .97
   max            <.96,.98>          .99
   max            <.194,.195>        .103
   max            <.201,.203>        .105
   max            <.204,.161>        .107
   max            <.205,.206>        .109
   max            <.104,.106>        .112
   max            <.108,.110>        .114
   max            <.113,.115>        .117
   max            <.116,.118>        .119
   max            <.199,.141>        .123
   max            <.207,.208>        .125
   max            <.209,.210>        .127
   max            <.211,.212>        .129
   max            <.124,.126>        .132
   max            <.128,.130>        .134
   max            <.133,.135>        .137
   max            <.136,.138>        .139
   max            <.202,.161>        .143
   max            <.209,.213>        .145
   max            <.214,.212>        .147
   max            <.215,.216>        .149
   max            <.144,.146>        .152
   max            <.148,.150>        .154
   max            <.153,.155>        .157
   max            <.156,.158>        .159
   max            <.205,.206>        .163
   max            <.214,.217>        .165
   max            <.218,.216>        .167
   max            <.219,.220>        .169
   max            <.164,.166>        .172
   max            <.168,.170>        .174
   max            <.173,.175>        .177
   max            <.176,.178>        .179
   ----------------------------------------

 Directions -  <<in,in,in,in,in,in,in,?>,<in,in,in,in,in,in,in,?>,<in,in,in,in,in,in,in,?>,<in,in,in,in,in,in,in,?>,<in,in,in,in,in,in,in,?>,<in,in,in,in,in,in,in,?>,<in,in,in,in,in,in,in,?>,<?,?,?,?,?,?,?,?>> ~ <<out,out,out>,<out,out,out>,<out,out,out>>

 Wiring -  <<.1,.181,.21,.186,.41,.190,.191,.221>,<.182,.183,.184,.187,.188,.192,.193,.222>,<.61,.185,.81,.189,.101,.194,.195,.223>,<.196,.197,.198,.200,.201,.203,.204,.224>,<.121,.199,.141,.202,.161,.205,.206,.225>,<.207,.208,.209,.213,.214,.217,.218,.226>,<.210,.211,.212,.215,.216,.219,.220,.227>,<.228,.229,.230,.231,.232,.233,.234,.235>> ~ <<.20,.40,.60>,<.80,.100,.120>,<.140,.160,.180>>

 Inputs -  .1 .181 .21 .186 .41 .190 .191 .221 .182 .183 .184 .187 .188 .192 .193 .222 .61 .185 .81 .189 .101 .194 .195 .223 .196 .197 .198 .200 .201 .203 .204 .224 .121 .199 .141 .202 .161 .205 .206 .225 .207 .208 .209 .213 .214 .217 .218 .226 .210 .211 .212 .215 .216 .219 .220 .227 .228 .229 .230 .231 .232 .233 .234 .235
