
   Name           Domain             Range
   ----------------------------------------
   ltn            <.1,0>             .2
   ----------------------------------------
   bit2uint       <.2>               .3
   ----------------------------------------
   MUXR 2         <.3,<.1,0>>        .4
   ----------------------------------------

 Directions -  in ~ out

 Wiring -  .1 ~ .4

 Inputs -  .1
